apiVersion: v1
kind: PersistentVolume
metadata:
  name: grafana-pv
spec:
  capacity:
    storage: 3Gi
  accessModes:
    - ReadWriteMany
  nfs:
    path: /nfs/k8s/grafana
    server: 172.31.40.193
  persistentVolumeReclaimPolicy: Retain
